# Generated by Django 5.1.3 on 2024-12-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_myuser_birthday_alter_myuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(blank=True, help_text='Обязательное поле. Не более 150 символов.', max_length=150, verbose_name='first name'),
        ),
    ]
