# Generated by Django 5.1.3 on 2024-12-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_myuser_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='img_path',
            field=models.CharField(default='img/no_image.png', max_length=128, verbose_name='Путь до изображения'),
        ),
    ]
