# Generated by Django 5.1.3 on 2024-12-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_myuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(help_text='Обязательное поле. Не более 150 символов.', max_length=150, verbose_name='first name'),
        ),
    ]
