# Generated by Django 5.1.3 on 2024-12-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_myuser_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='birthday',
            field=models.DateField(blank=True, help_text='Мы Вас поздравим и сделаем скидку :)', null=True, verbose_name='Дата рождения'),
        ),
    ]
