# Generated by Django 5.1.3 on 2024-12-10 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_equipment', '0005_alter_services_price'),
        ('users', '0013_alter_myuser_img_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('equipment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services_equipment.equipment')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services_equipment.services')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
