# Generated by Django 5.1.3 on 2024-12-10 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_equipment', '0005_alter_services_price'),
        ('users', '0014_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='img_path',
            field=models.ImageField(blank=True, default='no_image.png', upload_to='users/profile_photo/', verbose_name='Загрузите фото профиля'),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.DateTimeField(null=True, verbose_name='Дата и время окончания'),
        ),
        migrations.AlterField(
            model_name='session',
            name='equipment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services_equipment.equipment', verbose_name='Номер оборудования'),
        ),
        migrations.AlterField(
            model_name='session',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services_equipment.services', verbose_name='Номер услуги'),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время начала'),
        ),
        migrations.AlterField(
            model_name='session',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Номер пользователя'),
        ),
    ]
