# Generated by Django 5.1.3 on 2024-12-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_equipment', '0002_equipment_img_path_services_img_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='title',
        ),
        migrations.AddField(
            model_name='equipment',
            name='serviceability',
            field=models.BooleanField(default=True, verbose_name='Признак готовности к работе'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='type',
            field=models.CharField(default='Неопределенный тип', max_length=128, verbose_name='Тип оборудования'),
        ),
        migrations.AddField(
            model_name='services',
            name='weekday',
            field=models.BooleanField(default=True, verbose_name='Будний день'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='installed_apps_and_games',
            field=models.TextField(null=True, verbose_name='Установленные игры и приложения'),
        ),
    ]
