# Generated by Django 5.1.3 on 2024-12-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_equipment', '0003_remove_equipment_title_equipment_serviceability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='img_path',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='img_path',
            field=models.CharField(default='img/no_image.png', max_length=128, verbose_name='Путь до изображения'),
        ),
    ]
