# Generated by Django 5.1.3 on 2024-12-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_equipment', '0004_remove_services_img_path_alter_equipment_img_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена услуги за час'),
        ),
    ]
