# Generated by Django 5.1.3 on 2024-12-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_equipment', '0005_alter_services_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='img_path',
            field=models.ImageField(default='no_image.png', upload_to='equipments/', verbose_name='Путь до изображения'),
        ),
    ]
